### ISSUE TITLE
Epic: Refactor code base for enhanced modularity.

### ISSUE THREAD

**Issue by jonathanHuwP** [jonathanHuwP/hello-numerical-world-2021-11-15-sc#1]
# Definition of 'Done':
- [ ] Unit test pass
- [ ] Code review complete
- [ ] Integration/system tests pass
- [ ] Utility performance is at least 95% of pre-separation performance
- [ ] Utility usability demonstrated outside of heat equation application
# Tasks Required
- [ ] Task 1
- [ ] Task 2
