### ISSUE TITLE
Story: seperate the integration function

### ISSUE THREAD

**Issue by jonathanHuwP** [jonathanHuwP/hello-numerical-world-2021-11-15-sc#2]
# Definition of Done:
- [ ] Pass unit tests
- [ ] Pass integration tests
- [ ] Reproduce previous output withing numerical accuracy
# Tasks
- [ ] Run and store examples, to form tests.
- [ ]  Set up unit tests
- [ ] Generalize the interface, to allow multiple implementations
- [ ] Reimplement the existing integrator behind new interface
- [ ] Run all tests

**Comment by jonathanHuwP** [comment]
Carried out. File on server.

**Comment by jonathanHuwP** [comment]
Tests required for #1 added.
